In [1]:
import pandas as pd

In [3]:
df_job_uniqueness = pd.read_csv('transformed data/2-Job Uniqueness by Tech Tasks and Tools.csv')
df_job_uniqueness

,O*NET-SOC Code,Job Title,AVG_TECH_SKILL_UNIQUENESS_1to5,NUM_TECH_SKILLS,AVG_TECH_TYPE_UNIQUENESS_1to5,NUM_TECH_TYPES,AVG_TOOL_UNIQUENESS_1to5,NUM_TOOLS,AVG_TASK_UNIQUENESS_1to5,NUM_TASK_CONCEPTS,NUM_TASK_ROWS
0,11-1011.00,Chief Executives,1.285714,49,1.347826,23,1.000,7,3.290,31,31
1,11-1011.03,Chief Sustainability Officers,1.000000,21,1.125000,16,1.000,10,3.056,18,18
2,11-1021.00,General and Operations Managers,1.246575,146,1.732143,56,1.278,18,2.765,17,17
3,11-1031.00,Legislators,2.406250,32,1.500000,16,2.000,4,3.000,30,30
4,11-2011.00,Advertising and Promotions Managers,1.397260,73,1.296296,27,1.000,12,3.400,30,30
...,...,...,...,...,...,...,...,...,...,...,...
897,53-7071.00,Gas Compressor and Gas Pumping Station Operators,1.000000,6,1.333333,6,1.647,17,2.692,13,13
898,53-7072.00,"Pump Operators, Except Wellhead Pumpers",1.000000,7,1.285714,7,2.625,40,2.857,14,14
899,53-7073.00,Wellhead Pumpers,1.125000,8,1.142857,7,2.768,69,2.714,14,14
900,53-7081.00,Refuse and Recyclable Material Collectors,1.400000,10,2.000000,9,2.812,16,3.429,14,14
901,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.142857,7,1.166667,6,2.118,17,2.579,19,19

In [11]:
df_t3_uniqueness = df_job_uniqueness.copy()
df_t3_uniqueness['Mean T3 Uniqueness'] = (df_t3_uniqueness['AVG_TECH_SKILL_UNIQUENESS_1to5'] + df_t3_uniqueness['AVG_TOOL_UNIQUENESS_1to5'] +df_t3_uniqueness['AVG_TASK_UNIQUENESS_1to5']) / 3
df_t3_uniqueness = df_t3_uniqueness[['O*NET-SOC Code', 'Job Title', 'Mean T3 Uniqueness']]
df_t3_uniqueness

,O*NET-SOC Code,Job Title,Mean T3 Uniqueness
0,11-1011.00,Chief Executives,1.858571
1,11-1011.03,Chief Sustainability Officers,1.685333
2,11-1021.00,General and Operations Managers,1.763192
3,11-1031.00,Legislators,2.468750
4,11-2011.00,Advertising and Promotions Managers,1.932420
...,...,...,...
897,53-7071.00,Gas Compressor and Gas Pumping Station Operators,1.779667
898,53-7072.00,"Pump Operators, Except Wellhead Pumpers",2.160667
899,53-7073.00,Wellhead Pumpers,2.202333
900,53-7081.00,Refuse and Recyclable Material Collectors,2.547000
901,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.946619

In [14]:
df_t3_uniqueness.nsmallest(10, 'Mean T3 Uniqueness')

,O*NET-SOC Code,Job Title,Mean T3 Uniqueness
313,25-2058.00,"Special Education Teachers, Secondary School",1.058333
285,25-1067.00,"Sociology Teachers, Postsecondary",1.059977
272,25-1041.00,"Agricultural Sciences Teachers, Postsecondary",1.069889
270,25-1031.00,"Architecture Teachers, Postsecondary",1.078211
283,25-1065.00,"Political Science Teachers, Postsecondary",1.083966
269,25-1022.00,"Mathematical Science Teachers, Postsecondary",1.087000
271,25-1032.00,"Engineering Teachers, Postsecondary",1.097333
312,25-2057.00,"Special Education Teachers, Middle School",1.108333
307,25-2031.00,"Secondary School Teachers, Except Special and ...",1.114667
280,25-1062.00,"Area, Ethnic, and Cultural Studies Teachers, P...",1.116000

In [6]:
df_scaled_elements = pd.read_csv('transformed data/2-Prescaled Elements normalized comb level and import.csv')

# Have to go back in later and implement this change in the original notebook
df_scaled_elements.rename(columns={'Title': 'Job Title'}, inplace=True)

df_scaled_elements

,O*NET-SOC Code,Job Title,Conflict Situations,Consequence of Error,Contact With Others,Coordinate or Lead Others in Accomplishing Work Activities,Deal With External Customers or the Public in General,"Dealing With Unpleasant, Angry, or Discourteous People",Dealing with Violent or Physically Aggressive People,Degree of Automation,...,Perceptual Speed Combined,Visualization Combined,"Judging the Qualities of Objects, Services, or People Combined",Handling and Moving Objects Combined,Service Orientation Combined,"Organizing, Planning, and Prioritizing Work Combined",Oral Expression Combined,Persuasion Combined,Monitoring and Controlling Resources Combined,Spatial Orientation Combined
0,11-1011.00,Chief Executives,3.86,3.02,4.58,4.29,4.33,3.24,1.46,2.23,...,1.857143,1.965714,3.012486,1.255543,2.023657,3.869386,3.440000,3.035714,3.110357,1.027143
1,11-1011.03,Chief Sustainability Officers,3.04,2.15,4.41,4.22,3.85,2.41,1.19,1.56,...,1.378571,1.720000,2.783286,1.081714,2.044643,3.922271,3.035714,2.645714,2.978971,1.000000
2,11-1021.00,General and Operations Managers,3.35,2.52,4.63,4.48,4.49,3.24,1.62,2.31,...,1.443571,1.687500,2.718286,1.374286,2.002857,3.102857,2.765714,2.403571,2.846743,1.044286
3,11-2011.00,Advertising and Promotions Managers,3.15,2.19,4.68,4.11,4.19,2.92,1.14,2.01,...,1.738571,2.002857,2.239171,1.378000,1.984286,3.517886,3.205357,2.319200,1.668800,1.000000
4,11-2021.00,Marketing Managers,3.18,2.76,4.61,4.32,4.25,2.74,1.16,2.10,...,1.720000,1.857143,2.195157,1.042814,1.984286,3.804429,2.765714,2.720714,2.199000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,2.59,4.41,4.07,3.42,2.36,2.50,1.17,2.77,...,2.190000,1.687500,2.678286,3.227714,1.378571,2.558000,1.908571,1.378571,1.884129,1.268571
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",1.92,3.59,4.25,3.11,2.90,2.21,1.15,2.11,...,2.473214,1.928571,2.433514,3.151386,1.417943,3.017357,2.216429,1.417943,1.761829,1.339200
891,53-7073.00,Wellhead Pumpers,2.62,3.67,4.12,3.13,3.43,2.52,1.38,2.00,...,2.023657,1.780000,1.940000,2.533214,1.157143,2.819286,1.857143,1.178571,1.916671,1.300800
892,53-7081.00,Refuse and Recyclable Material Collectors,2.44,3.17,3.61,2.56,2.78,2.91,1.34,2.33,...,1.417943,1.482143,1.327314,2.862000,1.370629,1.371429,1.773486,1.285714,1.037886,1.417943
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",3.71,4.74,4.47,4.07,3.05,2.82,1.30,1.87,...,2.167771,1.857143,2.954029,3.597900,1.378571,2.734386,1.984286,1.302857,1.588343,1.500000

In [23]:
excluded_cols = ['O*NET-SOC Code', 'Job Title']
df_scaled_elems_avg = df_scaled_elements.copy()
df_scaled_elems_avg['Element Avg'] = df_scaled_elems_avg.drop(columns=excluded_cols).mean(axis=1)
df_scaled_elems_avg = df_scaled_elems_avg[['O*NET-SOC Code', 'Job Title', 'Element Avg']]
df_scaled_elems_avg

,O*NET-SOC Code,Job Title,Element Avg
0,11-1011.00,Chief Executives,2.442583
1,11-1011.03,Chief Sustainability Officers,2.210463
2,11-1021.00,General and Operations Managers,2.201566
3,11-2011.00,Advertising and Promotions Managers,2.054743
4,11-2021.00,Marketing Managers,2.122046
...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,2.326854
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",2.255412
891,53-7073.00,Wellhead Pumpers,2.192687
892,53-7081.00,Refuse and Recyclable Material Collectors,1.863213
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",2.424032

In [25]:
df_scaled_elems_avg.nsmallest(10, 'Element Avg')

,O*NET-SOC Code,Job Title,Element Avg
558,41-9012.00,Models,1.492215
531,39-5092.00,Manicurists and Pedicurists,1.587405
504,35-9021.00,Dishwashers,1.630410
524,39-3093.00,"Locker Room, Coatroom, and Dressing Room Atten...",1.631118
613,43-9081.00,Proofreaders and Copy Markers,1.656041
492,35-2011.00,"Cooks, Fast Food",1.668722
497,35-2021.00,Food Preparation Workers,1.681883
817,51-9031.00,"Cutters and Trimmers, Hand",1.682766
783,51-6031.00,Sewing Machine Operators,1.686925
782,51-6021.00,"Pressers, Textile, Garment, and Related Materials",1.693521

# All jobs condensed

In [26]:
all_jobs_df = pd.merge(df_t3_uniqueness, df_scaled_elems_avg, on=['O*NET-SOC Code', 'Job Title'], how='inner')
all_jobs_df

,O*NET-SOC Code,Job Title,Mean T3 Uniqueness,Element Avg
0,11-1011.00,Chief Executives,1.858571,2.442583
1,11-1011.03,Chief Sustainability Officers,1.685333,2.210463
2,11-1021.00,General and Operations Managers,1.763192,2.201566
3,11-2011.00,Advertising and Promotions Managers,1.932420,2.054743
4,11-2021.00,Marketing Managers,1.966776,2.122046
...,...,...,...,...
882,53-7071.00,Gas Compressor and Gas Pumping Station Operators,1.779667,2.326854
883,53-7072.00,"Pump Operators, Except Wellhead Pumpers",2.160667,2.255412
884,53-7073.00,Wellhead Pumpers,2.202333,2.192687
885,53-7081.00,Refuse and Recyclable Material Collectors,2.547000,1.863213
886,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.946619,2.424032

In [ ]:
sdf = pd.read_csv('ai support files/1/

# All Jobs together bigger

In [8]:
all_jobs_df = pd.merge(df_job_uniqueness, df_scaled_elements, on=['O*NET-SOC Code', 'Job Title'], how='inner')
all_jobs_df

,O*NET-SOC Code,Job Title,AVG_TECH_SKILL_UNIQUENESS_1to5,NUM_TECH_SKILLS,AVG_TECH_TYPE_UNIQUENESS_1to5,NUM_TECH_TYPES,AVG_TOOL_UNIQUENESS_1to5,NUM_TOOLS,AVG_TASK_UNIQUENESS_1to5,NUM_TASK_CONCEPTS,...,Perceptual Speed Combined,Visualization Combined,"Judging the Qualities of Objects, Services, or People Combined",Handling and Moving Objects Combined,Service Orientation Combined,"Organizing, Planning, and Prioritizing Work Combined",Oral Expression Combined,Persuasion Combined,Monitoring and Controlling Resources Combined,Spatial Orientation Combined
0,11-1011.00,Chief Executives,1.285714,49,1.347826,23,1.000,7,3.290,31,...,1.857143,1.965714,3.012486,1.255543,2.023657,3.869386,3.440000,3.035714,3.110357,1.027143
1,11-1011.03,Chief Sustainability Officers,1.000000,21,1.125000,16,1.000,10,3.056,18,...,1.378571,1.720000,2.783286,1.081714,2.044643,3.922271,3.035714,2.645714,2.978971,1.000000
2,11-1021.00,General and Operations Managers,1.246575,146,1.732143,56,1.278,18,2.765,17,...,1.443571,1.687500,2.718286,1.374286,2.002857,3.102857,2.765714,2.403571,2.846743,1.044286
3,11-2011.00,Advertising and Promotions Managers,1.397260,73,1.296296,27,1.000,12,3.400,30,...,1.738571,2.002857,2.239171,1.378000,1.984286,3.517886,3.205357,2.319200,1.668800,1.000000
4,11-2021.00,Marketing Managers,1.150327,153,1.717391,46,1.000,8,3.750,20,...,1.720000,1.857143,2.195157,1.042814,1.984286,3.804429,2.765714,2.720714,2.199000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,53-7071.00,Gas Compressor and Gas Pumping Station Operators,1.000000,6,1.333333,6,1.647,17,2.692,13,...,2.190000,1.687500,2.678286,3.227714,1.378571,2.558000,1.908571,1.378571,1.884129,1.268571
883,53-7072.00,"Pump Operators, Except Wellhead Pumpers",1.000000,7,1.285714,7,2.625,40,2.857,14,...,2.473214,1.928571,2.433514,3.151386,1.417943,3.017357,2.216429,1.417943,1.761829,1.339200
884,53-7073.00,Wellhead Pumpers,1.125000,8,1.142857,7,2.768,69,2.714,14,...,2.023657,1.780000,1.940000,2.533214,1.157143,2.819286,1.857143,1.178571,1.916671,1.300800
885,53-7081.00,Refuse and Recyclable Material Collectors,1.400000,10,2.000000,9,2.812,16,3.429,14,...,1.417943,1.482143,1.327314,2.862000,1.370629,1.371429,1.773486,1.285714,1.037886,1.417943
886,53-7121.00,"Tank Car, Truck, and Ship Loaders",1.142857,7,1.166667,6,2.118,17,2.579,19,...,2.167771,1.857143,2.954029,3.597900,1.378571,2.734386,1.984286,1.302857,1.588343,1.500000