In [1]:
import pandas as pd

In [2]:
df_occupation_data = pd.read_csv('ONET data/Occupation Data.csv')
df_task_statements = pd.read_csv('ONET data/Task Statements.csv')
df_skills = pd.read_csv('ONET data/Skills.csv')
df_abilities = pd.read_csv('ONET data/Abilities.csv')
df_work_activities = pd.read_csv('ONET data/Work Activities.csv')
df_knowledge = pd.read_csv('ONET data/Knowledge.csv')
df_work_context = pd.read_csv('ONET data/Work Context.csv')
df_tools_used = pd.read_csv('ONET data/Tools Used.csv')
df_technology_skills = pd.read_csv('ONET data/Technology Skills.csv')

# Titles DF

In [22]:
tasks_per_title = (
    df_task_statements
        .groupby("Title")["Task"]
        .nunique()
        .reset_index(name="Number of Tasks")
)

tasks_per_title

                                                 Title  Number of Tasks
0                             Accountants and Auditors               29
1                                               Actors               18
2                                            Actuaries               15
3                                       Acupuncturists               18
4                                    Acute Care Nurses               27
..                                                 ...              ...
918                   Wind Turbine Service Technicians               12
919  Woodworking Machine Setters, Operators, and Te...               25
920                        Word Processors and Typists               19
921                                Writers and Authors               20
922                 Zoologists and Wildlife Biologists               14

[923 rows x 2 columns]

In [39]:
tasks_per_title['Title'].nunique()

923

In [41]:
df_occupation_data

,O*NET-SOC Code,Title,Description
0,11-1011.00,Chief Executives,Determine and formulate policies and provide o...
1,11-1011.03,Chief Sustainability Officers,"Communicate and coordinate with management, sh..."
2,11-1021.00,General and Operations Managers,"Plan, direct, or coordinate the operations of ..."
3,11-1031.00,Legislators,"Develop, introduce, or enact laws and statutes..."
4,11-2011.00,Advertising and Promotions Managers,"Plan, direct, or coordinate advertising polici..."
...,...,...,...
1011,55-3014.00,Artillery and Missile Crew Members,"Target, fire, and maintain weapons used to des..."
1012,55-3015.00,Command and Control Center Specialists,"Operate and monitor communications, detection,..."
1013,55-3016.00,Infantry,Operate weapons and equipment in ground combat...
1014,55-3018.00,Special Forces,"Implement unconventional operations by air, la..."
1015,55-3019.00,Military Enlisted Tactical Operations and Air/...,All military enlisted tactical operations and ...

In [50]:
titles_master_df = pd.merge(tasks_per_title, df_occupation_data, on='Title', how='outer')
titles_master_df

,Title,Number of Tasks,O*NET-SOC Code,Description
0,Accountants and Auditors,29.0,13-2011.00,"Examine, analyze, and interpret accounting rec..."
1,Actors,18.0,27-2011.00,"Play parts in stage, television, radio, video,..."
2,Actuaries,15.0,15-2011.00,"Analyze statistical data, such as mortality, a..."
3,Acupuncturists,18.0,29-1291.00,"Diagnose, treat, and prevent disorders by stim..."
4,Acute Care Nurses,27.0,29-1141.01,Provide advanced nursing care for patients wit...
...,...,...,...,...
1011,"Woodworkers, All Other",NaN,51-7099.00,All woodworkers not listed separately.
1012,"Woodworking Machine Setters, Operators, and Te...",25.0,51-7042.00,"Set up, operate, or tend woodworking machines,..."
1013,Word Processors and Typists,19.0,43-9022.00,"Use word processor, computer, or typewriter to..."
1014,Writers and Authors,20.0,27-3043.00,"Originate and prepare written material, such a..."
1015,Zoologists and Wildlife Biologists,14.0,19-1023.00,"Study the origins, behavior, diseases, genetic..."

In [47]:
merged_df.isnull().sum()

Title               0
Number of Tasks    93
O*NET-SOC Code      0
Description         0
dtype: int64

# Task / Task ID mismatch?

In [57]:
df_task_statements

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source
0,11-1011.00,Chief Executives,8823,Direct or coordinate an organization's financi...,Core,95.0,08/2023,Incumbent
1,11-1011.00,Chief Executives,8824,"Confer with board members, organization offici...",Core,95.0,08/2023,Incumbent
2,11-1011.00,Chief Executives,8827,"Prepare budgets for approval, including those ...",Core,95.0,08/2023,Incumbent
3,11-1011.00,Chief Executives,8826,"Direct, plan, or implement policies, objective...",Core,94.0,08/2023,Incumbent
4,11-1011.00,Chief Executives,8834,Prepare or present reports concerning activiti...,Core,95.0,08/2023,Incumbent
...,...,...,...,...,...,...,...,...
18791,53-7121.00,"Tank Car, Truck, and Ship Loaders",12807,Unload cars containing liquids by connecting h...,Supplemental,85.0,08/2019,Incumbent
18792,53-7121.00,"Tank Car, Truck, and Ship Loaders",12804,"Clean interiors of tank cars or tank trucks, u...",Supplemental,85.0,08/2019,Incumbent
18793,53-7121.00,"Tank Car, Truck, and Ship Loaders",12803,Lower gauge rods into tanks or read meters to ...,Supplemental,85.0,08/2019,Incumbent
18794,53-7121.00,"Tank Car, Truck, and Ship Loaders",12805,Operate conveyors and equipment to transfer gr...,Supplemental,85.0,08/2019,Incumbent
18795,53-7121.00,"Tank Car, Truck, and Ship Loaders",12810,"Perform general warehouse activities, such as ...",Supplemental,85.0,08/2019,Incumbent

In [58]:
df_task_statements['Task'].nunique()

17537

In [59]:
df_task_statements['Task ID'].nunique()

18796

In [65]:
multiple_ids = (
    df_task_statements
        .groupby("Task")["Task ID"]
        .nunique()
        .reset_index(name="Number of IDs per task")
)

multiple_ids

,Task,Number of IDs per task
0,Accept and check containers of mail or parcels...,1
1,Accept credit applications and verify credit r...,1
2,Accept music requests from event guests.,1
3,"Accept payment from customers, and make change...",1
4,Accept payment on accounts.,1
...,...,...
17532,"Write, prepare, and deliver statements for the...",1
17533,"Write, review, or comment on documents, such a...",1
17534,"Write, review, or execute plans for testing ne...",1
17535,"Write, review, or maintain engineering documen...",1
17536,"Write, update, and maintain computer programs ...",1

In [71]:
multiple_ids['Number of IDs per task'].value_counts()

Number of IDs per task
1     17140
2       288
3        42
4        11
5         8
9         7
7         7
34        6
33        5
6         5
29        3
32        3
10        2
8         2
12        2
31        1
21        1
11        1
22        1
13        1
18        1
Name: count, dtype: int64

In [67]:
tasks_master_df = pd.merge(df_task_statements, multiple_ids, on='Task', how='outer')
tasks_master_df

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source,Number of IDs per task
0,43-9051.00,"Mail Clerks and Mail Machine Operators, Except...",13282,Accept and check containers of mail or parcels...,Core,85.0,07/2016,Incumbent,1
1,41-2012.00,Gambling Change Persons and Booth Cashiers,7009,Accept credit applications and verify credit r...,Supplemental,83.0,08/2019,Incumbent,1
2,27-2091.00,"Disc Jockeys, Except Radio",22604,Accept music requests from event guests.,NaN,NaN,11/2020,Analyst,1
3,35-3023.00,Fast Food and Counter Workers,23100,"Accept payment from customers, and make change...",Core,116.0,08/2025,Incumbent,1
4,43-4131.00,Loan Interviewers and Clerks,11304,Accept payment on accounts.,Supplemental,62.0,07/2017,Incumbent,1
...,...,...,...,...,...,...,...,...,...
18791,11-1031.00,Legislators,15284,"Write, prepare, and deliver statements for the...",NaN,NaN,06/2006,Analyst,1
18792,17-2112.01,Human Factors Engineers and Ergonomists,16372,"Write, review, or comment on documents, such a...",Core,20.0,08/2024,Occupational Expert,1
18793,15-1299.03,Document Management Specialists,16220,"Write, review, or execute plans for testing ne...",Core,20.0,08/2021,Occupational Expert,1
18794,17-2141.02,Automotive Engineers,16425,"Write, review, or maintain engineering documen...",Core,21.0,08/2022,Occupational Expert,1
18795,15-1251.00,Computer Programmers,1270,"Write, update, and maintain computer programs ...",Core,70.0,08/2018,Incumbent,1

In [68]:
tasks_master_df.isnull().sum()

O*NET-SOC Code               0
Title                        0
Task ID                      0
Task                         0
Task Type                  845
Incumbents Responding     1190
Date                         0
Domain Source                0
Number of IDs per task       0
dtype: int64

Is it a trailing zero problem?

In [76]:
sorted_tasks_master_df = tasks_master_df.sort_values(by=['Title', 'Task'])
sorted_tasks_master_df['Title_Task_ID'] = range(len(sorted_tasks_master_df))
sorted_tasks_master_df

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source,Number of IDs per task,Title_Task_ID
342,13-2011.00,Accountants and Auditors,21527,"Advise clients in areas such as compensation, ...",Supplemental,NaN,11/2020,Analyst - Transition,1,0
564,13-2011.00,Accountants and Auditors,21519,"Analyze business operations, trends, costs, re...",Core,NaN,11/2020,Analyst - Transition,1,1
1556,13-2011.00,Accountants and Auditors,21524,Audit payroll and personnel records to determi...,Core,NaN,11/2020,Analyst - Transition,1,2
2423,13-2011.00,Accountants and Auditors,21507,Collect and analyze data to detect deficient c...,Core,NaN,11/2020,Analyst - Transition,1,3
2957,13-2011.00,Accountants and Auditors,21526,"Compute taxes owed and prepare tax returns, en...",Supplemental,NaN,11/2020,Analyst - Transition,1,4
...,...,...,...,...,...,...,...,...,...,...
11427,19-1023.00,Zoologists and Wildlife Biologists,1499,Organize and conduct experimental studies with...,Supplemental,61.0,08/2023,Incumbent,1,18791
11818,19-1023.00,Zoologists and Wildlife Biologists,1498,"Perform administrative duties, such as fundrai...",Core,61.0,08/2023,Incumbent,1,18792
12997,19-1023.00,Zoologists and Wildlife Biologists,1502,Prepare collections of preserved specimens or ...,Supplemental,61.0,08/2023,Incumbent,1,18793
17046,19-1023.00,Zoologists and Wildlife Biologists,1492,"Study animals in their natural habitats, asses...",Core,61.0,08/2023,Incumbent,1,18794
17067,19-1023.00,Zoologists and Wildlife Biologists,1497,"Study characteristics of animals, such as orig...",Core,61.0,08/2023,Incumbent,1,18795

# Everything below here may need redone.

# TASKS DF

How many titles is each task associated with?

In [35]:
titles_per_task = (
    df_task_statements
        .groupby("Task")["Title"]
        .nunique()
        .reset_index(name="Number of Titles")
)

titles_per_task

                                                    Task  Number of Titles
0      Accept and check containers of mail or parcels...                 1
1      Accept credit applications and verify credit r...                 1
2               Accept music requests from event guests.                 1
3      Accept payment from customers, and make change...                 1
4                            Accept payment on accounts.                 1
...                                                  ...               ...
17532  Write, prepare, and deliver statements for the...                 1
17533  Write, review, or comment on documents, such a...                 1
17534  Write, review, or execute plans for testing ne...                 1
17535  Write, review, or maintain engineering documen...                 1
17536  Write, update, and maintain computer programs ...                 1

[17537 rows x 2 columns]

In [36]:
titles_per_task["Uniqueness Rank DENSE"] = (
    titles_per_task["Number of Titles"]
        .rank(method="dense", ascending=True)
)

titles_per_task = titles_per_task.sort_values("Number of Titles")

titles_per_task["Uniqueness Rank MIN"] = (
    titles_per_task["Number of Titles"]
        .rank(method="min", ascending=True)
        .astype(int)
)



titles_per_task

,Task,Number of Titles,Uniqueness Rank DENSE,Uniqueness Rank MIN
0,Accept and check containers of mail or parcels...,1,1.0,1
11612,Plan and implement projects for conservation o...,1,1.0,1
11613,Plan and implement revegetation of disturbed s...,1,1.0,1
11614,Plan and implement sales promotions or other m...,1,1.0,1
11616,"Plan and lay out repair work, using diagrams, ...",1,1.0,1
...,...,...,...,...
9108,Maintain regularly scheduled office hours to a...,34,21.0,17532
9125,"Maintain student attendance records, grades, a...",34,21.0,17532
25,Act as advisers to student organizations.,34,21.0,17532
2546,Compile bibliographies of specialized material...,34,21.0,17532
15298,Serve on academic or administrative committees...,34,21.0,17532

In [37]:
titles_per_task['Number of Titles'].nunique()

21

In [48]:
titles_per_task['Task'].nunique()

17537

In [54]:
tasks_master_df = pd.merge(titles_per_task, df_task_statements, on='Title', how='outer')
tasks_master_df

KeyError: 'Title'