In [1]:
import pandas as pd
df_technology_skills = pd.read_csv('ONET data/Technology Skills.csv')
df_tools_used = pd.read_csv('ONET data/Tools Used.csv')
df_task_statements = pd.read_csv('ONET data/Task Statements.csv')
df_skills = pd.read_csv('ONET data/Skills.csv')
df_abilities = pd.read_csv('ONET data/Abilities.csv')


df_occupation_data = pd.read_csv('ONET data/Occupation Data.csv')
df_work_activities = pd.read_csv('ONET data/Work Activities.csv')
df_knowledge = pd.read_csv('ONET data/Knowledge.csv')
df_work_context = pd.read_csv('ONET data/Work Context.csv')

In [2]:
df_occupation_data

,O*NET-SOC Code,Title,Description
0,11-1011.00,Chief Executives,Determine and formulate policies and provide o...
1,11-1011.03,Chief Sustainability Officers,"Communicate and coordinate with management, sh..."
2,11-1021.00,General and Operations Managers,"Plan, direct, or coordinate the operations of ..."
3,11-1031.00,Legislators,"Develop, introduce, or enact laws and statutes..."
4,11-2011.00,Advertising and Promotions Managers,"Plan, direct, or coordinate advertising polici..."
...,...,...,...
1011,55-3014.00,Artillery and Missile Crew Members,"Target, fire, and maintain weapons used to des..."
1012,55-3015.00,Command and Control Center Specialists,"Operate and monitor communications, detection,..."
1013,55-3016.00,Infantry,Operate weapons and equipment in ground combat...
1014,55-3018.00,Special Forces,"Implement unconventional operations by air, la..."
1015,55-3019.00,Military Enlisted Tactical Operations and Air/...,All military enlisted tactical operations and ...

In [4]:
aliases_df = pd.read_csv('Occupation_Alias_Table.csv')
aliases_df

,O*NET-SOC Code,Title,Alias
0,11-1011.00,Chief Executives,Chief Executive
1,11-1011.00,Chief Executives,CEO
2,11-1011.03,Chief Sustainability Officers,Chief Sustainability Officer
3,11-1011.03,Chief Sustainability Officers,Chief Sustainability
4,11-1011.03,Chief Sustainability Officers,CSO
...,...,...,...
1547,55-3015.00,Command and Control Center Specialists,Command & Control Center Specialists
1548,55-3015.00,Command and Control Center Specialists,Command and Control Center
1549,55-3015.00,Command and Control Center Specialists,Command and Control Center Specialist
1550,55-3018.00,Special Forces,Special Force
1551,55-3019.00,Military Enlisted Tactical Operations and Air/...,Military Enlisted Tactical Operations & Air/We...

In [5]:
aliases_df = pd.read_csv('Occupation_Alias_Table_v2.csv')
aliases_df

,O*NET-SOC Code,Title,Alias
0,11-1011.00,Chief Executives,Chief Executive
1,11-1011.00,Chief Executives,Chief Execs
2,11-1011.03,Chief Sustainability Officers,Chief Sustainability Officer
3,11-1011.03,Chief Sustainability Officers,Chief Sustainability
4,11-1011.03,Chief Sustainability Officers,CSO
...,...,...,...
3415,55-3019.00,Military Enlisted Tactical Operations and Air/...,Military Enlisted Tactical Operations and Air/...
3416,55-3019.00,Military Enlisted Tactical Operations and Air/...,Military Enlisted Tactical Operations and Air/...
3417,55-3019.00,Military Enlisted Tactical Operations and Air/...,Military Enlisted Tactical Operations & Air/We...
3418,55-3019.00,Military Enlisted Tactical Operations and Air/...,Military Enlisted Tactical Operations / Air/We...
3419,55-3019.00,Military Enlisted Tactical Operations and Air/...,Military Enlisted Tactical Operations and Air/...