In [1]:
import pandas as pd
df_technology_skills = pd.read_csv('ONET data/Technology Skills.csv')
df_tools_used = pd.read_csv('ONET data/Tools Used.csv')
df_task_statements = pd.read_csv('ONET data/Task Statements.csv')
df_skills = pd.read_csv('ONET data/Skills.csv')
df_abilities = pd.read_csv('ONET data/Abilities.csv')
df_occupation_data = pd.read_csv('ONET data/Occupation Data.csv')

df_work_activities = pd.read_csv('ONET data/Work Activities.csv')
df_knowledge = pd.read_csv('ONET data/Knowledge.csv')
df_work_context = pd.read_csv('ONET data/Work Context.csv')

In [2]:
df_work_activities

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,4.A.1.a.1,Getting Information,IM,Importance,4.56,29.0,0.1559,4.2369,4.8756,N,NaN,08/2023,Incumbent
1,11-1011.00,Chief Executives,4.A.1.a.1,Getting Information,LV,Level,4.89,30.0,0.1727,4.5393,5.2458,N,N,08/2023,Incumbent
2,11-1011.00,Chief Executives,4.A.1.a.2,"Monitoring Processes, Materials, or Surroundings",IM,Importance,4.25,30.0,0.2125,3.8130,4.6823,N,NaN,08/2023,Incumbent
3,11-1011.00,Chief Executives,4.A.1.a.2,"Monitoring Processes, Materials, or Surroundings",LV,Level,5.21,30.0,0.3872,4.4133,5.9971,N,N,08/2023,Incumbent
4,11-1011.00,Chief Executives,4.A.1.b.1,"Identifying Objects, Actions, and Events",IM,Importance,4.23,29.0,0.1544,3.9180,4.5507,N,NaN,08/2023,Incumbent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73303,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.A.4.c.1,Performing Administrative Activities,LV,Level,2.27,27.0,0.3184,1.6108,2.9197,N,N,08/2019,Incumbent
73304,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.A.4.c.2,Staffing Organizational Units,IM,Importance,1.93,27.0,0.2132,1.4962,2.3726,N,NaN,08/2019,Incumbent
73305,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.A.4.c.2,Staffing Organizational Units,LV,Level,1.60,27.0,0.2965,0.9936,2.2125,N,N,08/2019,Incumbent
73306,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.A.4.c.3,Monitoring and Controlling Resources,IM,Importance,2.56,27.0,0.2582,2.0266,3.0881,N,NaN,08/2019,Incumbent
73307,53-7121.00,"Tank Car, Truck, and Ship Loaders",4.A.4.c.3,Monitoring and Controlling Resources,LV,Level,2.64,27.0,0.3350,1.9556,3.3329,N,N,08/2019,Incumbent

Aggregate the same way as 1-4 and 1-5. Easy.

In [3]:
df = df_work_activities.copy()

# Create combined column label
df["Skill_Scale"] = df["Element Name"] + " " + df["Scale Name"]

In [4]:
df_wide = df.pivot_table(
    index=["O*NET-SOC Code", "Title"],
    columns="Skill_Scale",
    values="Data Value"
).reset_index()

In [5]:
df_wide

Skill_Scale,O*NET-SOC Code,Title,Analyzing Data or Information Importance,Analyzing Data or Information Level,Assisting and Caring for Others Importance,Assisting and Caring for Others Level,Coaching and Developing Others Importance,Coaching and Developing Others Level,Communicating with People Outside the Organization Importance,Communicating with People Outside the Organization Level,...,Staffing Organizational Units Importance,Staffing Organizational Units Level,Thinking Creatively Importance,Thinking Creatively Level,Training and Teaching Others Importance,Training and Teaching Others Level,Updating and Using Relevant Knowledge Importance,Updating and Using Relevant Knowledge Level,Working with Computers Importance,Working with Computers Level
0,11-1011.00,Chief Executives,4.38,4.84,3.31,3.10,4.71,5.85,4.55,5.47,...,3.78,4.80,4.32,4.45,4.01,4.76,4.31,5.09,4.17,3.03
1,11-1011.03,Chief Sustainability Officers,4.22,4.81,2.74,2.67,3.93,4.78,4.48,6.11,...,3.26,4.26,4.33,4.85,3.63,4.22,4.30,5.59,4.15,3.22
2,11-1021.00,General and Operations Managers,4.04,4.27,3.02,3.03,3.91,4.53,3.57,4.42,...,3.70,4.33,3.70,3.95,3.41,3.79,3.80,4.17,4.46,4.15
3,11-2011.00,Advertising and Promotions Managers,3.26,4.06,2.37,2.00,2.62,3.28,4.37,5.70,...,2.29,2.31,4.05,4.73,2.74,2.83,3.78,4.49,4.61,3.94
4,11-2021.00,Marketing Managers,3.75,4.04,2.44,2.21,3.36,3.74,4.20,5.60,...,2.25,2.18,4.28,4.71,3.14,3.34,3.83,4.52,4.40,3.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,53-7071.00,Gas Compressor and Gas Pumping Station Operators,3.68,4.43,2.54,2.15,2.98,2.76,3.04,2.68,...,1.84,0.70,3.12,3.52,3.73,4.22,4.05,4.75,3.85,3.47
890,53-7072.00,"Pump Operators, Except Wellhead Pumpers",3.96,3.97,3.09,2.58,2.86,2.69,2.74,3.00,...,2.18,2.06,3.41,3.99,3.15,3.04,3.99,4.36,2.69,1.98
891,53-7073.00,Wellhead Pumpers,3.70,3.80,3.04,2.97,3.16,3.31,2.72,2.44,...,1.94,1.66,3.34,3.52,3.48,3.56,3.31,3.90,3.53,3.55
892,53-7081.00,Refuse and Recyclable Material Collectors,1.61,1.03,1.69,1.10,2.10,1.80,2.39,2.44,...,1.00,0.01,1.57,0.98,1.69,1.22,2.17,2.39,1.55,0.96
893,53-7121.00,"Tank Car, Truck, and Ship Loaders",3.85,3.90,2.87,3.11,3.07,3.28,2.61,2.47,...,1.93,1.60,3.44,3.74,3.45,3.85,3.84,4.48,2.82,2.58

In [6]:
df_wide.to_csv('transformed data/7-Activities Pivoted.csv', index=False)

In [ ]:
# Z Scores