In [1]:
import pandas as pd

In [2]:
equity_df = pd.read_csv('equity_value_data.csv')
equity_df

                    timestamp  close_equity                           user_id
0        2016-11-16T00:00:00Z         48.16  bcef4fa9b0bdf22bcf7deae708decf03
1        2016-11-17T00:00:00Z         48.16  bcef4fa9b0bdf22bcf7deae708decf03
2        2016-11-18T00:00:00Z         48.16  bcef4fa9b0bdf22bcf7deae708decf03
3        2016-11-21T00:00:00Z         48.16  bcef4fa9b0bdf22bcf7deae708decf03
4        2016-11-22T00:00:00Z         48.16  bcef4fa9b0bdf22bcf7deae708decf03
...                       ...           ...                               ...
1119153  2017-08-14T00:00:00Z       2270.71  98580360c4fb5b0ec511cd87f0d429ed
1119154  2017-08-15T00:00:00Z       2275.02  98580360c4fb5b0ec511cd87f0d429ed
1119155  2017-08-16T00:00:00Z       2282.03  98580360c4fb5b0ec511cd87f0d429ed
1119156  2017-08-17T00:00:00Z       2237.45  98580360c4fb5b0ec511cd87f0d429ed
1119157  2017-08-18T00:00:00Z       2227.35  98580360c4fb5b0ec511cd87f0d429ed

[1119158 rows x 3 columns]

In [23]:
equity_df['date'] = pd.to_datetime(equity_df['timestamp']).dt.date
equity_df

,timestamp,close_equity,user_id,date
0,2016-11-16T00:00:00Z,48.16,bcef4fa9b0bdf22bcf7deae708decf03,2016-11-16
1,2016-11-17T00:00:00Z,48.16,bcef4fa9b0bdf22bcf7deae708decf03,2016-11-17
2,2016-11-18T00:00:00Z,48.16,bcef4fa9b0bdf22bcf7deae708decf03,2016-11-18
3,2016-11-21T00:00:00Z,48.16,bcef4fa9b0bdf22bcf7deae708decf03,2016-11-21
4,2016-11-22T00:00:00Z,48.16,bcef4fa9b0bdf22bcf7deae708decf03,2016-11-22
...,...,...,...,...
1119153,2017-08-14T00:00:00Z,2270.71,98580360c4fb5b0ec511cd87f0d429ed,2017-08-14
1119154,2017-08-15T00:00:00Z,2275.02,98580360c4fb5b0ec511cd87f0d429ed,2017-08-15
1119155,2017-08-16T00:00:00Z,2282.03,98580360c4fb5b0ec511cd87f0d429ed,2017-08-16
1119156,2017-08-17T00:00:00Z,2237.45,98580360c4fb5b0ec511cd87f0d429ed,2017-08-17
1119157,2017-08-18T00:00:00Z,2227.35,98580360c4fb5b0ec511cd87f0d429ed,2017-08-18

Is it possible for there to be multiple trades on a given day? I would assume so.

In [16]:
equity_df.isnull().sum()

timestamp       0
close_equity    0
user_id         0
dtype: int64

In [5]:
equity_df['user_id'].nunique()

5584

In [7]:
equity_df['timestamp'].nunique()

255

In [8]:
255 * 5584

1423920

So, not every user has the same number of time stamps. This makes sense as almost certainly some users joined after the beginning of the dataset.

In [3]:
features_df = pd.read_csv('features_data.csv')
features_df

,risk_tolerance,investment_experience,liquidity_needs,platform,time_spent,instrument_type_first_traded,first_deposit_amount,time_horizon,user_id
0,high_risk_tolerance,limited_investment_exp,very_important_liq_need,Android,33.129417,stock,40.0,med_time_horizon,895044c23edc821881e87da749c01034
1,med_risk_tolerance,limited_investment_exp,very_important_liq_need,Android,16.573517,stock,200.0,short_time_horizon,458b1d95441ced242949deefe8e4b638
2,med_risk_tolerance,limited_investment_exp,very_important_liq_need,iOS,10.008367,stock,25.0,long_time_horizon,c7936f653d293479e034865db9bb932f
3,med_risk_tolerance,limited_investment_exp,very_important_liq_need,Android,1.031633,stock,100.0,short_time_horizon,b255d4bd6c9ba194d3a350b3e76c6393
4,high_risk_tolerance,limited_investment_exp,very_important_liq_need,Android,8.187250,stock,20.0,long_time_horizon,4a168225e89375b8de605cbc0977ae91
...,...,...,...,...,...,...,...,...,...
5579,high_risk_tolerance,limited_investment_exp,very_important_liq_need,Android,8.339283,stock,300.0,long_time_horizon,03880c726d8a4e5db006afe4119ad974
5580,med_risk_tolerance,limited_investment_exp,somewhat_important_liq_need,iOS,7.241383,stock,100.0,short_time_horizon,ae8315109657f44852b24c6bca4decd6
5581,med_risk_tolerance,no_investment_exp,very_important_liq_need,both,22.967167,stock,50.0,short_time_horizon,f29c174989f9737058fe808fcf264135
5582,med_risk_tolerance,limited_investment_exp,somewhat_important_liq_need,iOS,10.338417,stock,100.0,long_time_horizon,24843497d1de88b2e7233f694436cb3a
5583,high_risk_tolerance,limited_investment_exp,somewhat_important_liq_need,iOS,18.470950,stock,50.0,long_time_horizon,49ee0531ee9dfbce0e7d9afa1c3d86f4

Below I will add a few columns to provide greater context about each user.

In [29]:
# Date of each user's first trade
features_df['first_trade'] = (
    equity_df
    .groupby('user_id')['date']
    .transform('min')
)

# Date of each user's last trade
features_df['last_trade'] = (
    equity_df
    .groupby('user_id')['date']
    .transform('max')
)

features_df

,risk_tolerance,investment_experience,liquidity_needs,platform,time_spent,instrument_type_first_traded,first_deposit_amount,time_horizon,user_id,first_trade,last_trade
0,high_risk_tolerance,limited_investment_exp,very_important_liq_need,Android,33.129417,stock,40.0,med_time_horizon,895044c23edc821881e87da749c01034,2016-11-16,2017-07-12
1,med_risk_tolerance,limited_investment_exp,very_important_liq_need,Android,16.573517,stock,200.0,short_time_horizon,458b1d95441ced242949deefe8e4b638,2016-11-16,2017-07-12
2,med_risk_tolerance,limited_investment_exp,very_important_liq_need,iOS,10.008367,stock,25.0,long_time_horizon,c7936f653d293479e034865db9bb932f,2016-11-16,2017-07-12
3,med_risk_tolerance,limited_investment_exp,very_important_liq_need,Android,1.031633,stock,100.0,short_time_horizon,b255d4bd6c9ba194d3a350b3e76c6393,2016-11-16,2017-07-12
4,high_risk_tolerance,limited_investment_exp,very_important_liq_need,Android,8.187250,stock,20.0,long_time_horizon,4a168225e89375b8de605cbc0977ae91,2016-11-16,2017-07-12
...,...,...,...,...,...,...,...,...,...,...,...
5579,high_risk_tolerance,limited_investment_exp,very_important_liq_need,Android,8.339283,stock,300.0,long_time_horizon,03880c726d8a4e5db006afe4119ad974,2016-08-16,2017-08-15
5580,med_risk_tolerance,limited_investment_exp,somewhat_important_liq_need,iOS,7.241383,stock,100.0,short_time_horizon,ae8315109657f44852b24c6bca4decd6,2016-08-16,2017-08-15
5581,med_risk_tolerance,no_investment_exp,very_important_liq_need,both,22.967167,stock,50.0,short_time_horizon,f29c174989f9737058fe808fcf264135,2016-08-16,2017-08-15
5582,med_risk_tolerance,limited_investment_exp,somewhat_important_liq_need,iOS,10.338417,stock,100.0,long_time_horizon,24843497d1de88b2e7233f694436cb3a,2016-08-16,2017-08-15
5583,high_risk_tolerance,limited_investment_exp,somewhat_important_liq_need,iOS,18.470950,stock,50.0,long_time_horizon,49ee0531ee9dfbce0e7d9afa1c3d86f4,2016-08-16,2017-08-15

In [17]:
features_df.isnull().sum()

risk_tolerance                  0
investment_experience           0
liquidity_needs                 0
platform                        0
time_spent                      0
instrument_type_first_traded    0
first_deposit_amount            0
time_horizon                    0
user_id                         0
dtype: int64

In [6]:
features_df['user_id'].nunique()

5584

In [14]:
features_df['instrument_type_first_traded'].value_counts()

instrument_type_first_traded
stock       4827
etp          383
adr          197
mlp           55
reit          55
cef           20
wrt           16
0             13
rlt            9
lp             8
tracking       1
Name: count, dtype: int64

In [15]:
features_df['risk_tolerance'].value_counts()

risk_tolerance
high_risk_tolerance    3566
med_risk_tolerance     1779
low_risk_tolerance      239
Name: count, dtype: int64

In [11]:
features_df['investment_experience'].value_counts()

investment_experience
limited_investment_exp      2578
no_investment_exp           1796
good_investment_exp         1134
extensive_investment_exp      76
Name: count, dtype: int64

In [12]:
features_df['liquidity_needs'].value_counts()

liquidity_needs
very_important_liq_need        4217
somewhat_important_liq_need    1109
not_important_liq_need          258
Name: count, dtype: int64

In [13]:
features_df['time_horizon'].value_counts()

time_horizon
short_time_horizon    2833
long_time_horizon     1833
med_time_horizon       918
Name: count, dtype: int64

What does risk tolerance look like relative to experience, and vice versa?

In [19]:
risk_experience = features_df.groupby('risk_tolerance')['investment_experience'].value_counts()
risk_experience

risk_tolerance       investment_experience
high_risk_tolerance  limited_investment_exp      1685
                     no_investment_exp            973
                     good_investment_exp          854
                     extensive_investment_exp      54
low_risk_tolerance   no_investment_exp            106
                     limited_investment_exp        84
                     good_investment_exp           42
                     extensive_investment_exp       7
med_risk_tolerance   limited_investment_exp       809
                     no_investment_exp            717
                     good_investment_exp          238
                     extensive_investment_exp      15
Name: count, dtype: int64

In [21]:
experience_by_risk = (
    features_df
    .groupby('risk_tolerance')['investment_experience']
    .value_counts(normalize=True)
    .mul(100)
    .rename('percentage')
)

experience_by_risk

risk_tolerance       investment_experience
high_risk_tolerance  limited_investment_exp      47.251823
                     no_investment_exp           27.285474
                     good_investment_exp         23.948402
                     extensive_investment_exp     1.514302
low_risk_tolerance   no_investment_exp           44.351464
                     limited_investment_exp      35.146444
                     good_investment_exp         17.573222
                     extensive_investment_exp     2.928870
med_risk_tolerance   limited_investment_exp      45.474986
                     no_investment_exp           40.303541
                     good_investment_exp         13.378302
                     extensive_investment_exp     0.843170
Name: percentage, dtype: float64

In [22]:
risk_by_experience = (
    features_df
    .groupby('investment_experience')['risk_tolerance']
    .value_counts(normalize=True)
    .mul(100)
    .rename('percentage')
)

risk_by_experience

investment_experience     risk_tolerance
extensive_investment_exp  high_risk_tolerance    71.052632
                          med_risk_tolerance     19.736842
                          low_risk_tolerance      9.210526
good_investment_exp       high_risk_tolerance    75.308642
                          med_risk_tolerance     20.987654
                          low_risk_tolerance      3.703704
limited_investment_exp    high_risk_tolerance    65.360745
                          med_risk_tolerance     31.380915
                          low_risk_tolerance      3.258340
no_investment_exp         high_risk_tolerance    54.175947
                          med_risk_tolerance     39.922049
                          low_risk_tolerance      5.902004
Name: percentage, dtype: float64

Low risk tolerance is rare at all levels of experience. The greater trend is that with greater experience, the middle option falls away, and investors are more likely to have higher risk tolerance.