In this notebook we will compare the results between models. We will also see which statistics correlate to higher inaccuracies.

In [1]:
import pandas as pd
mlb_players = pd.read_csv('Pitchers Cleaned.csv')
results_dtree = pd.read_csv('Results DTree no GS.csv')
results_etc = pd.read_csv('Results ETC no GS.csv')
results_gbc = pd.read_csv('Results GBC no GS.csv')
results_logreg = pd.read_csv('Results LogReg no GS.csv')
results_rfc = pd.read_csv('Results RFC no GS.csv')
results_svc = pd.read_csv('Results SVC no GS.csv')

In [24]:
results_comparison = pd.DataFrame()
results_comparison['Player'] = mlb_players['Player']
results_comparison['Hall of Fame'] = mlb_players['Hall of Fame']

results_comparison['DTree Prediction'] = results_dtree['Prediction']
results_comparison['DTree Correct'] = results_dtree['Prediction Correct']
results_comparison['DTree Confidence'] = results_dtree['Prediction Confidence']

results_comparison['ETC Prediction'] = results_etc['Prediction']
results_comparison['ETC Correct'] = results_etc['Prediction Correct']
results_comparison['ETC Confidence'] = results_etc['Prediction Confidence']

results_comparison['GBC Prediction'] = results_gbc['Prediction']
results_comparison['GBC Correct'] = results_gbc['Prediction Correct']
results_comparison['GBC Confidence'] = results_gbc['Prediction Confidence']

results_comparison['Logreg Prediction'] = results_logreg['Prediction']
results_comparison['Logreg Correct'] = results_logreg['Prediction Correct']
results_comparison['Logreg Confidence'] = results_logreg['Prediction Confidence']

results_comparison['RFC Prediction'] = results_rfc['Prediction']
results_comparison['RFC Correct'] = results_rfc['Prediction Correct']
results_comparison['RFC Confidence'] = results_rfc['Prediction Confidence']

results_comparison['SVC Prediction'] = results_svc['Prediction']
results_comparison['SVC Correct'] = results_svc['Prediction Correct']
results_comparison['SVC Confidence'] = results_svc['Prediction Confidence']





prediction_cols = ['DTree Prediction', 'ETC Prediction', 'GBC Prediction', 'Logreg Prediction', 'RFC Prediction', 'SVC Prediction']
results_comparison['Number of Positive Predictions'] = results_comparison[prediction_cols].eq(1).sum(axis=1)
results_comparison['Number of Negative Predictions'] = results_comparison[prediction_cols].eq(0).sum(axis=1)



#results_comparison['Number of Correct Predictions'] = results_comparison[columns_to_check].eq(1).sum(axis=1)


columns_to_check = ['DTree Correct', 'ETC Correct', 'GBC Correct', 'Logreg Correct', 'RFC Correct', 'SVC Correct']


# Calculate the sum of '1's in the specified columns for each row
count_of_ones = results_comparison[columns_to_check].sum(axis=1)

# Calculate the percentage
results_comparison['Percent of Predictions Correct'] = (count_of_ones / len(columns_to_check)) * 100




results_comparison['Mean Prediction Confidence'] = (
    results_comparison['DTree Confidence'] +
    results_comparison['ETC Confidence'] +
    results_comparison['GBC Confidence'] +
    results_comparison['Logreg Confidence'] +
    results_comparison['RFC Confidence'] +
    results_comparison['SVC Confidence']) / 6

results_comparison['Pct Correct Minus Confidence'] = results_comparison['Percent of Predictions Correct'] - results_comparison['Mean Prediction Confidence']

results_comparison

,Player,Hall of Fame,DTree Prediction,DTree Correct,DTree Confidence,ETC Prediction,ETC Correct,ETC Confidence,GBC Prediction,GBC Correct,...,RFC Correct,RFC Confidence,SVC Prediction,SVC Correct,SVC Confidence,Number of Positive Predictions,Number of Negative Predictions,Percent of Predictions Correct,Mean Prediction Confidence,Pct Correct Minus Confidence
0,Cy Young,1,1,1,1.0,1,1,0.91,1,1,...,1,0.86,1,1,0.812674,6,0,100.000000,0.930056,99.069944
1,Pud Galvin,1,0,0,1.0,1,1,0.73,0,0,...,1,0.68,1,1,0.993500,4,2,66.666667,0.815157,65.851509
2,Walter Johnson,1,1,1,1.0,1,1,0.96,1,1,...,1,0.88,1,1,0.991771,6,0,100.000000,0.971742,99.028258
3,Phil Niekro,1,1,1,0.0,1,1,0.81,1,1,...,1,0.77,1,1,0.988360,6,0,100.000000,0.753539,99.246461
4,Nolan Ryan,1,1,1,1.0,1,1,0.86,1,1,...,1,0.82,1,1,0.997005,6,0,100.000000,0.935636,99.064364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,Charlie Robertson,0,0,1,1.0,0,1,0.99,0,1,...,1,1.00,0,1,0.955076,0,6,100.000000,0.990715,99.009285
1211,Sammy Ellis,0,0,1,1.0,0,1,1.00,0,1,...,1,1.00,0,1,0.959009,0,6,100.000000,0.993070,99.006930
1212,Lil Stoner,0,0,1,1.0,0,1,1.00,0,1,...,1,1.00,0,1,0.960723,0,6,100.000000,0.993333,99.006667
1213,Johnny Humphries,0,0,1,1.0,0,1,1.00,0,1,...,1,1.00,0,1,0.954236,0,6,100.000000,0.992215,99.007785
1214,Scott Karl,0,0,1,1.0,0,1,1.00,0,1,...,1,1.00,0,1,0.960516,0,6,100.000000,0.993308,99.006692

In [25]:
results_comparison.nsmallest(10, 'Pct Correct Minus Confidence')

,Player,Hall of Fame,DTree Prediction,DTree Correct,DTree Confidence,ETC Prediction,ETC Correct,ETC Confidence,GBC Prediction,GBC Correct,...,RFC Correct,RFC Confidence,SVC Prediction,SVC Correct,SVC Confidence,Number of Positive Predictions,Number of Negative Predictions,Percent of Predictions Correct,Mean Prediction Confidence,Pct Correct Minus Confidence
105,Jesse Haines,1,0,0,1.0,0,0,0.93,0,0,...,0,1.00,0,0,0.968629,0,6,0.0,0.979674,-0.979674
15,Roger Clemens,0,1,0,1.0,1,0,0.94,1,0,...,0,0.94,1,0,0.985884,6,0,0.0,0.977528,-0.977528
91,Rube Marquard,1,0,0,1.0,0,0,0.94,0,0,...,0,0.98,0,0,0.953114,0,6,0.0,0.958746,-0.958746
257,John Ward,1,0,0,1.0,0,0,0.86,0,0,...,0,0.83,0,0,0.961727,0,6,0.0,0.940579,-0.940579
986,Babe Ruth,1,0,0,1.0,0,0,0.84,0,0,...,0,0.89,0,0,0.955437,0,6,0.0,0.940326,-0.940326
653,Andy Cooper,1,0,0,1.0,0,0,0.87,0,0,...,0,0.90,0,0,0.958597,0,6,0.0,0.895122,-0.895122
1174,Bruce Sutter,1,0,0,1.0,0,0,0.77,0,0,...,0,0.86,0,0,0.955220,0,6,0.0,0.892687,-0.892687
449,Dizzy Dean,1,0,0,1.0,0,0,0.81,0,0,...,0,0.77,0,0,0.957385,0,6,0.0,0.890588,-0.890588
246,Lefty Gomez,1,0,0,1.0,0,0,0.88,0,0,...,0,0.83,0,0,0.965267,0,6,0.0,0.887081,-0.887081
152,Jack Chesbro,1,0,0,1.0,0,0,0.85,0,0,...,0,0.86,0,0,0.965615,0,6,0.0,0.886875,-0.886875

In [15]:
results_comparison.nsmallest(10, 'Number of Correct Predictions')

,Player,DTree Prediction,DTree Correct,DTree Confidence,ETC Prediction,ETC Correct,ETC Confidence,GBC Prediction,GBC Correct,GBC Confidence,...,Logreg Confidence,RFC Prediction,RFC Correct,RFC Confidence,SVC Prediction,SVC Correct,SVC Confidence,Number of Correct Predictions,percentage_of_ones,Mean Prediction Confidence
15,Roger Clemens,1,0,1.0,1,0,0.94,1,0,0.999338,...,0.999948,1,0,0.94,1,0,0.985884,0,0.0,0.977528
30,Jack Powell,1,0,1.0,1,0,0.65,1,0,0.891484,...,0.964730,1,0,0.69,1,0,0.600016,0,0.0,0.799372
33,Jim McCormick,1,0,1.0,1,0,0.58,1,0,0.835301,...,0.965222,1,0,0.71,1,0,0.487867,0,0.0,0.763065
49,Jack Morris,0,0,0.0,0,0,0.74,0,0,0.881159,...,0.759291,0,0,0.72,0,0,0.780977,0,0.0,0.646904
78,Joe McGinnity,0,0,1.0,0,0,0.59,0,0,0.928740,...,0.503476,0,0,0.56,0,0,0.945961,0,0.0,0.754696
91,Rube Marquard,0,0,1.0,0,0,0.94,0,0,0.995225,...,0.884138,0,0,0.98,0,0,0.953114,0,0.0,0.958746
105,Jesse Haines,0,0,1.0,0,0,0.93,0,0,0.992968,...,0.986450,0,0,1.00,0,0,0.968629,0,0.0,0.979674
152,Jack Chesbro,0,0,1.0,0,0,0.85,0,0,0.949720,...,0.695917,0,0,0.86,0,0,0.965615,0,0.0,0.886875
158,Bob Lemon,0,0,1.0,0,0,0.83,0,0,0.921965,...,0.854407,0,0,0.70,0,0,0.969866,0,0.0,0.879373
181,Roy Halladay,0,0,1.0,0,0,0.78,0,0,0.812165,...,0.940302,0,0,0.77,0,0,0.962061,0,0.0,0.877421

In [26]:
hof_no = results_comparison[results_comparison['Hall of Fame'] == 0]
hof_no.nsmallest(10, 'Pct Correct Minus Confidence')

,Player,Hall of Fame,DTree Prediction,DTree Correct,DTree Confidence,ETC Prediction,ETC Correct,ETC Confidence,GBC Prediction,GBC Correct,...,RFC Correct,RFC Confidence,SVC Prediction,SVC Correct,SVC Confidence,Number of Positive Predictions,Number of Negative Predictions,Percent of Predictions Correct,Mean Prediction Confidence,Pct Correct Minus Confidence
15,Roger Clemens,0,1,0,1.0,1,0,0.94,1,0,...,0,0.94,1,0,0.985884,6,0,0.000000,0.977528,-0.977528
30,Jack Powell,0,1,0,1.0,1,0,0.65,1,0,...,0,0.69,1,0,0.600016,6,0,0.000000,0.799372,-0.799372
33,Jim McCormick,0,1,0,1.0,1,0,0.58,1,0,...,0,0.71,1,0,0.487867,6,0,0.000000,0.763065,-0.763065
19,Tommy John,0,1,0,1.0,1,0,0.83,1,0,...,0,0.90,1,0,0.939200,5,1,16.666667,0.935476,15.731191
23,Tony Mullane,0,1,0,1.0,1,0,0.65,1,0,...,0,0.75,1,0,0.864675,5,1,16.666667,0.835412,15.831255
98,Curt Schilling,0,0,1,1.0,1,0,0.66,1,0,...,0,0.57,0,1,0.899192,4,2,33.333333,0.763857,32.569476
44,Jack Quinn,0,1,0,1.0,1,0,0.71,1,0,...,0,0.59,0,1,0.802812,4,2,33.333333,0.735294,32.598040
34,Frank Tanana,0,1,0,1.0,1,0,0.54,0,1,...,0,0.40,1,0,0.652422,4,2,33.333333,0.670522,32.662811
72,Luis Tiant,0,0,1,0.0,1,0,0.56,1,0,...,0,0.61,0,1,0.903269,4,2,33.333333,0.646701,32.686632
14,Bobby Mathews,0,0,1,1.0,1,0,0.57,0,1,...,0,0.56,1,0,0.979122,3,3,50.000000,0.845980,49.154020

In [27]:
mlb_players_exp = mlb_players.copy()
mlb_players_exp['Percent of Predictions Correct'] = results_comparison['Percent of Predictions Correct']
mlb_players_exp['Mean Prediction Confidence'] = results_comparison['Mean Prediction Confidence']
mlb_players_exp['Pct Correct Minus Confidence'] = results_comparison['Pct Correct Minus Confidence']
mlb_players_exp

,Player,Debut Year,Debut Age,Retirement Year,Retirement Age,Career Length,Wins,Losses,Win Percentage,Total Decisions,...,WHIP,H9,HR9,BB9,SO9,SO/BB,Hall of Fame,Percent of Predictions Correct,Mean Prediction Confidence,Pct Correct Minus Confidence
0,Cy Young,1890,23,1911,44,21,511,315,0.619,826,...,1.130,8.7,0.2,1.5,3.4,2.30,1,100.000000,0.930056,99.069944
1,Pud Galvin,1875,18,1892,35,17,365,310,0.541,675,...,1.191,9.6,0.2,1.1,2.7,2.43,1,66.666667,0.815157,65.851509
2,Walter Johnson,1907,19,1927,39,20,417,279,0.599,696,...,1.061,7.5,0.1,2.1,5.3,2.57,1,100.000000,0.971742,99.028258
3,Phil Niekro,1964,25,1987,48,23,318,274,0.537,592,...,1.268,8.4,0.8,3.0,5.6,1.85,1,100.000000,0.753539,99.246461
4,Nolan Ryan,1966,19,1993,46,27,324,292,0.526,616,...,1.247,6.6,0.5,4.7,9.5,2.04,1,100.000000,0.935636,99.064364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,Charlie Robertson,1919,23,1928,32,9,49,80,0.380,129,...,1.518,10.3,0.3,3.4,2.8,0.82,0,100.000000,0.990715,99.009285
1211,Sammy Ellis,1962,21,1969,28,7,63,58,0.521,121,...,1.340,8.7,1.1,3.4,6.1,1.79,0,100.000000,0.993070,99.006930
1212,Lil Stoner,1922,23,1931,32,9,50,57,0.467,107,...,1.548,10.6,0.6,3.4,2.7,0.80,0,100.000000,0.993333,99.006667
1213,Johnny Humphries,1938,23,1946,31,8,52,63,0.452,115,...,1.394,9.2,0.4,3.4,2.8,0.85,0,100.000000,0.992215,99.007785
1214,Scott Karl,1995,23,2000,28,5,54,56,0.491,110,...,1.530,10.5,1.1,3.3,4.6,1.39,0,100.000000,0.993308,99.006692

In [32]:
mlb_players_exp_np = mlb_players_exp.drop('Player', axis=1)
correlations = mlb_players_exp_np.corrwith(mlb_players_exp['Percent of Predictions Correct'])
correlations

Debut Year                        0.084893
Debut Age                         0.097839
Retirement Year                   0.054384
Retirement Age                   -0.196436
Career Length                    -0.259727
Wins                             -0.358646
Losses                           -0.235018
Win Percentage                   -0.281810
Total Decisions                  -0.319524
Earned Run Average                0.253462
Total Games                      -0.218349
Games Started                    -0.246241
Relief Appearances               -0.040166
Complete Games                   -0.252417
Shutouts                         -0.275987
Saves                            -0.150390
Innings Pitched                  -0.320785
Hits Allowed                     -0.289573
Runs Allowed                     -0.248437
Earned Runs Allowed              -0.226159
Home Runs Allowed                -0.088353
Walks Allowed                    -0.204262
Intentional Walks Allowed        -0.032815
Strikeouts                       -0.285142
Batters Hit By Pitch             -0.158818
Balks                            -0.025327
Wild Pitches                     -0.156193
BF                               -0.304052
ERA+                             -0.371412
FIP                               0.235782
WHIP                              0.261819
H9                                0.178350
HR9                               0.122277
BB9                               0.154483
SO9                              -0.061969
SO/BB                            -0.191013
Hall of Fame                     -0.616325
Percent of Predictions Correct    1.000000
Mean Prediction Confidence        0.610276
Pct Correct Minus Confidence      0.999995
dtype: float64

In [34]:
mlb_players_exp_np = mlb_players_exp.drop('Player', axis=1)
correlations = mlb_players_exp_np.corrwith(mlb_players_exp['Hall of Fame'])

    # Or, sort by correlation directly (e.g., to see positive correlations first)
ranked_correlations = correlations.sort_values(ascending=False)
ranked_correlations

Hall of Fame                      1.000000
Wins                              0.560882
Shutouts                          0.521171
Innings Pitched                   0.517680
Total Decisions                   0.512441
BF                                0.492521
Strikeouts                        0.483310
ERA+                              0.465536
Hits Allowed                      0.451233
Complete Games                    0.418502
Games Started                     0.411353
Losses                            0.397410
Runs Allowed                      0.375604
Earned Runs Allowed               0.367956
Walks Allowed                     0.365457
Career Length                     0.349344
Total Games                       0.327431
Win Percentage                    0.322134
Retirement Age                    0.282824
Wild Pitches                      0.245161
SO/BB                             0.244592
Batters Hit By Pitch              0.222738
Home Runs Allowed                 0.194496
Saves                             0.172511
Intentional Walks Allowed         0.110503
SO9                               0.107713
Balks                             0.098798
Relief Appearances                0.032342
Retirement Year                  -0.053279
Debut Year                       -0.093735
Debut Age                        -0.099854
HR9                              -0.126338
BB9                              -0.167423
H9                               -0.261368
FIP                              -0.284274
Earned Run Average               -0.311417
WHIP                             -0.338048
Mean Prediction Confidence       -0.553226
Pct Correct Minus Confidence     -0.615624
Percent of Predictions Correct   -0.616325
dtype: float64