In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.metrics import median_absolute_error
from sklearn.model_selection import GridSearchCV

In [2]:
no_dummies = pd.read_csv('Step 4 - Final Dataset without dummies.csv')

In [3]:
scout_car = pd.read_csv('Step 4 - Final Dataset with dummies.csv')
scout_car

,Price,KM,Registration,Horsepower (kW),Previous Owners,Inspection new,Warranty (months),# of Doors,# of Seats,Displacement (cc),...,Country version_Poland,Country version_Spain,Upholstery Material_Full leather,Upholstery Material_Other,Upholstery Material_Part leather,Upholstery Material_Velour,Upholstery Material_alcantara,Upholstery Color_Brown,Upholstery Color_Grey,Upholstery Color_Other
0,15770,56013.0,2016.0,66.0,2,1,0.0,5.0,5.0,1422.0,...,0,0,0,0,0,0,0,0,0,0
1,14500,80000.0,2017.0,141.0,0,0,0.0,3.0,4.0,1798.0,...,0,0,0,0,0,0,0,0,1,0
2,14640,83450.0,2016.0,85.0,1,0,0.0,5.0,4.0,1598.0,...,0,0,0,0,0,0,0,0,0,0
3,14500,73000.0,2016.0,66.0,1,0,0.0,3.0,4.0,1422.0,...,0,0,0,0,0,0,0,0,0,0
4,16790,16200.0,2016.0,66.0,1,1,0.0,5.0,5.0,1422.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15095,39950,10.0,2016.0,147.0,0,0,0.0,5.0,5.0,1997.0,...,0,0,1,0,0,0,0,0,0,0
15096,39885,9900.0,2019.0,165.0,1,0,0.0,5.0,5.0,1798.0,...,0,0,0,0,0,0,0,0,0,0
15097,39875,15.0,2019.0,146.0,1,1,0.0,5.0,7.0,1997.0,...,0,0,1,0,0,0,0,0,0,0
15098,39700,10.0,2019.0,147.0,0,0,0.0,5.0,7.0,1997.0,...,0,0,0,0,1,0,0,0,0,0
15099,40999,10.0,2019.0,165.0,1,1,0.0,5.0,5.0,1798.0,...,0,0,1,0,0,0,0,1,0,0

# Unadjusted Linear Regression

In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.metrics import median_absolute_error
from sklearn.model_selection import GridSearchCV
from scipy import stats

# Features
X = scout_car.drop(columns=['Price'])

# Target
y = scout_car['Price']

# Split into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

linreg = LinearRegression()
linreg.fit(X_train, y_train)

LinearRegression()

In [5]:
y_pred = linreg.predict(X_test)
y_pred

array([32146.23914589, 12762.95249367, 38571.99685046, ...,
       10776.03822156,  4506.85477134, 20633.00547796])

In [6]:
from sklearn.metrics import r2_score, mean_squared_error
print(f"R-squared: {r2_score(y_test, y_pred)}")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred)}")
print(f"Mean Absolute Error: {mean_absolute_error(y_test, y_pred)}")
print(f"Median Absolute Error: {median_absolute_error(y_test, y_pred)}")

R-squared: 0.8990543254481328
Mean Squared Error: 5721650.4440968735
Mean Absolute Error: 1660.9032370987397
Median Absolute Error: 1196.4021015975159

In [ ]:
# As a new dataframe, Pull from no_dummies only indices that were in X_test
# Then match ['make_model']

,KM,Registration,Horsepower (kW),Previous Owners,Inspection new,Warranty (months),# of Doors,# of Seats,Displacement (cc),Cylinders,...,Country version_Poland,Country version_Spain,Upholstery Material_Full leather,Upholstery Material_Other,Upholstery Material_Part leather,Upholstery Material_Velour,Upholstery Material_alcantara,Upholstery Color_Brown,Upholstery Color_Grey,Upholstery Color_Other
14845,120.0,2018.0,118.0,1,0,0.0,5.0,7.0,1598.0,4.0,...,0,0,1,0,0,0,0,0,0,1
14120,5.0,2019.0,56.0,1,1,0.0,5.0,5.0,898.0,4.0,...,0,0,0,1,0,0,0,0,0,0
14860,15.0,2019.0,146.0,1,1,0.0,5.0,7.0,1997.0,4.0,...,0,0,1,0,0,0,0,0,0,0
884,12900.0,2017.0,70.0,1,0,0.0,5.0,5.0,999.0,4.0,...,0,0,0,0,0,0,0,0,0,1
411,40000.0,2016.0,85.0,0,0,0.0,3.0,4.0,1598.0,4.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,56539.0,2016.0,70.0,0,0,0.0,5.0,5.0,999.0,4.0,...,0,0,0,0,0,0,0,0,0,0
668,35100.0,2016.0,70.0,1,1,12.0,3.0,4.0,999.0,4.0,...,0,0,0,0,0,0,0,0,0,0
8028,30000.0,2016.0,66.0,1,1,60.0,5.0,5.0,1398.0,4.0,...,0,0,0,0,0,0,0,0,0,0
8495,51000.0,2016.0,51.0,1,0,0.0,3.0,5.0,1229.0,4.0,...,0,0,0,0,0,0,0,0,0,0
3877,22000.0,2018.0,85.0,0,0,0.0,5.0,5.0,1598.0,4.0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
#results_df = pd.DataFrame({'Actual Price': y_test, 'Predicted Price': y_pred})
linreg_1_results = pd.DataFrame()
#linreg_1_results['make_model'] = X_test["make_model"].values
linreg_1_results['Actual Price'] = y_test
linreg_1_results['Predicted Price'] = np.round(y_pred).astype(int)
linreg_1_results['Error'] = linreg_1_results['Predicted Price'] - linreg_1_results['Actual Price']
linreg_1_results['Squared Error'] = linreg_1_results['Error'] ** 2
linreg_1_results['Absolute Error'] = linreg_1_results['Error'].abs()
linreg_1_results

       Actual Price  Predicted Price  Error  Squared Error  Absolute Error
14845         34985            32146  -2839        8059921            2839
14120         11280            12763   1483        2199289            1483
14860         38875            38572   -303          91809             303
884           14500            15857   1357        1841449            1357
411           15900            17041   1141        1301881            1141
...             ...              ...    ...            ...             ...
499           13700            13529   -171          29241             171
668           12451            13219    768         589824             768
8028          12990            10776  -2214        4901796            2214
8495           7650             4507  -3143        9878449            3143
3877          19450            20633   1183        1399489            1183

[3020 rows x 5 columns]

In [16]:
linreg_1_results['Absolute Error'].mean()

np.float64(1660.903311258278)

In [18]:
linreg_1_results['Absolute Error'].median()

np.float64(1196.5)

In [7]:
linreg_1_results['Squared Error'].mean()

np.float64(5721598.413907285)

In [17]:
linreg_1_results['Squared Error'].median()

np.float64(1431612.5)

In [8]:
linreg_1_results['Error'].nlargest(10)

8471     21818
10336    13317
3035     10610
10400     9975
724       7805
10673     7791
10381     7266
10072     7143
6137      6865
14669     6700
Name: Error, dtype: int64

# Linear Regression with K-Fold Cross Validation

# Ridge

# Lasso

# Comparing Results