In [1]:
import pandas as pd

In [2]:
military_power = pd.read_excel('World military power.xlsx')
military_power

,Military Strength,Military Strength Power Index,Aircraft Strength,Aircraft Strength value,Fighter/Interceptor Strength,Fighter/Interceptor Strength value,Attack Aircraft Strength,Attack Aircraft Strength value,Transport Aircraft Fleet Strength,Transport Aircraft Fleet Strength value,...,Total Population,Total Population value,Total Square Land Area,Total Square Land Area value,Total Coastline Coverage,Total Coastline Coverage value,Total Waterway Coverage,Total Waterway Coverage value,Total Border Coverage,Total Border Coverage value
0,Afghanistan,1.3444,Afghanistan,260,Afghanistan,0,Afghanistan,25,Afghanistan,30,...,Afghanistan,"3,49,40,837",Afghanistan,"6,52,230",Afghanistan,0,Afghanistan,1200,Afghanistan,5987.0
1,Albania,2.3137,Albania,19,Albania,0,Albania,0,Albania,0,...,Albania,"30,57,220",Albania,28748,Albania,362,Albania,41,Albania,691.0
2,Algeria,0.4659,Algeria,551,Algeria,103,Algeria,22,Algeria,59,...,Algeria,"4,16,57,488",Algeria,"23,81,741",Algeria,998,Algeria,0,Algeria,6734.0
3,Angola,0.8379,Angola,295,Angola,72,Angola,18,Angola,30,...,Angola,"3,03,55,880",Angola,"12,46,700",Angola,1600,Angola,1300,Angola,5369.0
4,Argentina,0.6521,Argentina,227,Argentina,24,Argentina,7,Argentina,9,...,Argentina,"4,46,94,198",Argentina,"27,80,400",Argentina,4989,Argentina,11000,Argentina,11968.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,Venezuela,0.6449,Venezuela,260,Venezuela,38,Venezuela,0,Venezuela,52,...,Venezuela,"3,16,89,176",Venezuela,"9,12,050",Venezuela,2800,Venezuela,7100,Venezuela,5267.0
134,Vietnam,0.3559,Vietnam,293,Vietnam,77,Vietnam,0,Vietnam,38,...,Vietnam,"9,70,40,334",Vietnam,"3,31,210",Vietnam,3444,Vietnam,17702,Vietnam,4616.0
135,Yemen,1.2412,Yemen,169,Yemen,77,Yemen,0,Yemen,8,...,Yemen,"2,86,67,230",Yemen,"5,27,968",Yemen,1906,Yemen,0,Yemen,1601.0
136,Zambia,1.6464,Zambia,108,Zambia,18,Zambia,0,Zambia,11,...,Zambia,"1,64,45,079",Zambia,"7,52,618",NaN,NaN,Zambia,2250,Zambia,6043.0
137,Zimbabwe,1.7577,Zimbabwe,90,Zimbabwe,10,Zimbabwe,0,Zimbabwe,14,...,Zimbabwe,"1,40,30,368",Zimbabwe,"3,90,757",NaN,NaN,Zimbabwe,0,Zimbabwe,3229.0

In [3]:
military_power.columns

Index(['Military Strength', 'Military Strength Power Index',
       'Aircraft Strength', 'Aircraft Strength value',
       'Fighter/Interceptor Strength', 'Fighter/Interceptor Strength value',
       'Attack Aircraft Strength', 'Attack Aircraft Strength value',
       'Transport Aircraft Fleet Strength',
       'Transport Aircraft Fleet Strength value', 'Trainer Aircraft Fleet',
       'Trainer Aircraft Fleet value', 'Helicopter Fleet Strength',
       'Helicopter Fleet Strength value', 'Attack Helicopter Fleet Strength',
       'Attack Helicopter Fleet Strength value', 'Tank Strength',
       'Tank Strength value', 'AFV/APC Strength', 'AFV/APC Strength value',
       'Self-Propelled Artillery Strength',
       'Self-Propelled Artillery Strength value', 'Towed Artillery Strength',
       'Towed Artillery Strength value', 'Rocket Projector Strength',
       'Rocket Projector Strength value', 'Navy Fleet Strengths',
       'Navy Fleet Strengths value', 'Aircraft Carrier Fleet Strength',
       'Aircraft Carrier Fleet Strength value', 'Submarine Fleet Strength',
       'Submarine Fleet Strength value', 'Destroyer Fleet Strength',
       'Destroyer Fleet Strength value', 'Frigate Fleet Strength',
       'Frigate Fleet Strength value', 'defense spending budget',
       'defense spending budget value', 'External Debt', 'External Debt value',
       'Airport Totals', 'Airport Totals value', 'Oil Production',
       'Oil Production value', 'Oil Consumption', 'Oil Consumption value',
       'Proven Oil Reserves', 'Proven Oil Reserves value',
       'Available Manpower', 'Available Manpower value', 'Total Population',
       'Total Population value', 'Total Square Land Area',
       'Total Square Land Area value', 'Total Coastline Coverage',
       'Total Coastline Coverage value', 'Total Waterway Coverage',
       'Total Waterway Coverage value', 'Total Border Coverage',
       'Total Border Coverage value'],
      dtype='object')

In [4]:
# Rename the first column to represent country
military_power.rename(columns={'Military Strength': 'Country'}, inplace=True)

# Word to search for in column names
target_word = 'value'

# Hard-code these columns to keep
specific_cols_to_keep = ['Country', 'Military Strength Power Index']

# Create a list of columns to keep
columns_to_keep = []
for col in military_power.columns:
    if target_word in col or col in specific_cols_to_keep:
        columns_to_keep.append(col)

# Filter the DataFrame
military_power = military_power[columns_to_keep]

# Word to remove
word_to_remove = 'value'

# Remove the word 'value' from all column names for visual appeal
military_power.columns = military_power.columns.str.replace(word_to_remove, '')


military_power.columns = (
    military_power.columns
    .str.replace(word_to_remove, '', regex=False)  # safer: no regex behavior
    .str.strip()                                  # remove leading/trailing whitespace
    .str.replace(r'\s+', ' ', regex=True)         # collapse multiple spaces into one
)

# Remove all commas from the entire DataFrame
military_power = military_power.applymap(lambda x: x.replace(',', '') if isinstance(x, str) else x)

# Convert columns to numeric
excluded_column = 'Country'
columns_to_convert = [col for col in military_power.columns if col != excluded_column]
for col in columns_to_convert:
    military_power[col] = pd.to_numeric(military_power[col], errors='coerce')

military_power

/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_10600/579168762.py:34: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  military_power = military_power.applymap(lambda x: x.replace(',', '') if isinstance(x, str) else x)

,Country,Military Strength Power Index,Aircraft Strength,Fighter/Interceptor Strength,Attack Aircraft Strength,Transport Aircraft Fleet Strength,Trainer Aircraft Fleet,Helicopter Fleet Strength,Attack Helicopter Fleet Strength,Tank Strength,...,Airport Totals,Oil Production,Oil Consumption,Proven Oil Reserves,Available Manpower,Total Population,Total Square Land Area,Total Coastline Coverage,Total Waterway Coverage,Total Border Coverage
0,Afghanistan,1.3444,260,0,25,30,0,187,0,0,...,43,0,5500,0,14325743,34940837,652230,0.0,1200,5987.0
1,Albania,2.3137,19,0,0,0,0,19,0,0,...,4,16000,42500,168300000,1519438,3057220,28748,362.0,41,691.0
2,Algeria,0.4659,551,103,22,59,87,257,45,880,...,157,1306000,325000,12200000000,20741263,41657488,2381741,998.0,0,6734.0
3,Angola,0.8379,295,72,18,30,47,126,15,379,...,176,1666000,82300,8273000000,6244205,30355880,1246700,1600.0,1300,5369.0
4,Argentina,0.6521,227,24,7,9,64,100,0,370,...,1138,479400,685000,2185000000,20179430,44694198,2780400,4989.0,11000,11968.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,Venezuela,0.6449,260,38,0,52,82,86,10,390,...,444,2007000,575000,300900000000,14260129,31689176,912050,2800.0,7100,5267.0
134,Vietnam,0.3559,293,77,0,38,36,138,25,2615,...,45,271400,525000,4400000000,51043216,97040334,331210,3444.0,17702,4616.0
135,Yemen,1.2412,169,77,0,8,21,61,14,620,...,57,12260,145000,3000000000,11266221,28667230,527968,1906.0,0,1601.0
136,Zambia,1.6464,108,18,0,11,52,27,0,75,...,88,0,21000,0,6166905,16445079,752618,NaN,2250,6043.0
137,Zimbabwe,1.7577,90,10,0,14,38,28,6,42,...,196,0,19500,0,5584086,14030368,390757,NaN,0,3229.0

In [9]:
military_power.columns

Index(['Country', 'Military Strength Power Index', 'Aircraft Strength',
       'Fighter/Interceptor Strength', 'Attack Aircraft Strength',
       'Transport Aircraft Fleet Strength', 'Trainer Aircraft Fleet',
       'Helicopter Fleet Strength', 'Attack Helicopter Fleet Strength',
       'Tank Strength', 'AFV/APC Strength',
       'Self-Propelled Artillery Strength', 'Towed Artillery Strength',
       'Rocket Projector Strength', 'Navy Fleet Strengths',
       'Aircraft Carrier Fleet Strength', 'Submarine Fleet Strength',
       'Destroyer Fleet Strength', 'Frigate Fleet Strength',
       'defense spending budget', 'External Debt', 'Airport Totals',
       'Oil Production', 'Oil Consumption', 'Proven Oil Reserves',
       'Available Manpower', 'Total Population', 'Total Square Land Area',
       'Total Coastline Coverage', 'Total Waterway Coverage',
       'Total Border Coverage'],
      dtype='object')

In [10]:
military_power_exp = pd.DataFrame()
military_power_exp['Country'] = military_power['Country']
military_power_exp['Manpower Per Population'] = military_power['Available Manpower'] / military_power['Total Population']
military_power_exp['Oil Production Surplus or Deficit'] = military_power['Oil Production'] - military_power['Oil Consumption']
military_power_exp

         Country  Manpower Per Population  Oil Production Surplus or Deficit
0    Afghanistan                   0.4100                              -5500
1        Albania                   0.4970                             -26500
2        Algeria                   0.4979                             981000
3         Angola                   0.2057                            1583700
4      Argentina                   0.4515                            -205600
..           ...                      ...                                ...
133    Venezuela                   0.4500                            1432000
134      Vietnam                   0.5260                            -253600
135        Yemen                   0.3930                            -132740
136       Zambia                   0.3750                             -21000
137     Zimbabwe                   0.3980                             -19500

[138 rows x 3 columns]

In [6]:
military_power_exp.nlargest(10, 'Manpower Per Population')

                    Country  Manpower Per Population
105               Singapore                   0.6700
118                   Syria                   0.6400
68                Lithuania                   0.6370
15   Bosnia and Herzegovina                   0.6220
128    United Arab Emirates                   0.6000
75                 Mongolia                   0.5860
74                  Moldova                   0.5860
51                     Iran                   0.5700
9                   Bahrain                   0.5669
61                   Kuwait                   0.5630

In [7]:
military_power_exp.nsmallest(10, 'Manpower Per Population')

          Country  Manpower Per Population
78     Mozambique                   0.1700
121      Tanzania                   0.1850
3          Angola                   0.2057
115      Suriname                   0.2220
104  Sierra Leone                   0.2270
80        Namibia                   0.2300
13         Bhutan                   0.2307
76     Montenegro                   0.2380
108       Somalia                   0.2400
98          Qatar                   0.2590

In [11]:
military_power_exp.nlargest(10, 'Oil Production Surplus or Deficit')

,Country,Manpower Per Population,Oil Production Surplus or Deficit
101,Russia,0.4900,7355000
102,Saudi Arabia,0.5350,6130000
52,Iraq,0.4080,3629000
128,United Arab Emirates,0.6000,2599000
51,Iran,0.5700,2469000
61,Kuwait,0.5630,2408000
86,Nigeria,0.3790,1671000
3,Angola,0.2057,1583700
59,Kazakhstan,0.4580,1532000
22,Canada,0.4490,1477000

In [12]:
military_power_exp.nsmallest(10, 'Oil Production Surplus or Deficit')

           Country  Manpower Per Population  Oil Production Surplus or Deficit
130  United States                   0.4400                          -10648000
26           China                   0.5437                           -9662000
49           India                   0.4800                           -4266100
57           Japan                   0.4270                           -3996159
110    South Korea                   0.5000                           -2800000
43         Germany                   0.4600                           -2456590
40          France                   0.4470                           -1584830
105      Singapore                   0.6700                           -1340000
112          Spain                   0.4690                           -1223748
55           Italy                   0.4500                           -1222470

In [4]:
# Rename the first column to represent country
military_power.rename(columns={'Military Strength': 'Country'}, inplace=True)

# Word to search for in column names
target_word = 'value'

# Hard-code these columns to keep
specific_cols_to_keep = ['Country', 'Military Strength Power Index']

# Create a list of columns to keep
columns_to_keep = []
for col in military_power.columns:
    if target_word in col or col in specific_cols_to_keep:
        columns_to_keep.append(col)

# Filter the DataFrame
military_power = military_power[columns_to_keep]

# Word to remove
word_to_remove = 'value'

# Remove the word 'value' from all column names for visual appeal
military_power.columns = military_power.columns.str.replace(word_to_remove, '')

# Remove all commas from the entire DataFrame
military_power = military_power.applymap(lambda x: x.replace(',', '') if isinstance(x, str) else x)

# Convert columns to numeric
excluded_column = 'Country'
columns_to_convert = [col for col in military_power.columns if col != excluded_column]
for col in columns_to_convert:
    military_power[col] = pd.to_numeric(military_power[col], errors='coerce')

military_power

/var/folders/cf/4zrkk0lx1nbdx9tpklpk4jc00000gn/T/ipykernel_10550/218750918.py:26: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  military_power = military_power.applymap(lambda x: x.replace(',', '') if isinstance(x, str) else x)

,Country,Military Strength Power Index,Aircraft Strength,Fighter/Interceptor Strength,Attack Aircraft Strength,Transport Aircraft Fleet Strength,Trainer Aircraft Fleet,Helicopter Fleet Strength,Attack Helicopter Fleet Strength,Tank Strength,...,Airport Totals,Oil Production,Oil Consumption,Proven Oil Reserves,Available Manpower,Total Population,Total Square Land Area,Total Coastline Coverage,Total Waterway Coverage,Total Border Coverage
0,Afghanistan,1.3444,260,0,25,30,0,187,0,0,...,43,0,5500,0,14325743,34940837,652230,0.0,1200,5987.0
1,Albania,2.3137,19,0,0,0,0,19,0,0,...,4,16000,42500,168300000,1519438,3057220,28748,362.0,41,691.0
2,Algeria,0.4659,551,103,22,59,87,257,45,880,...,157,1306000,325000,12200000000,20741263,41657488,2381741,998.0,0,6734.0
3,Angola,0.8379,295,72,18,30,47,126,15,379,...,176,1666000,82300,8273000000,6244205,30355880,1246700,1600.0,1300,5369.0
4,Argentina,0.6521,227,24,7,9,64,100,0,370,...,1138,479400,685000,2185000000,20179430,44694198,2780400,4989.0,11000,11968.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,Venezuela,0.6449,260,38,0,52,82,86,10,390,...,444,2007000,575000,300900000000,14260129,31689176,912050,2800.0,7100,5267.0
134,Vietnam,0.3559,293,77,0,38,36,138,25,2615,...,45,271400,525000,4400000000,51043216,97040334,331210,3444.0,17702,4616.0
135,Yemen,1.2412,169,77,0,8,21,61,14,620,...,57,12260,145000,3000000000,11266221,28667230,527968,1906.0,0,1601.0
136,Zambia,1.6464,108,18,0,11,52,27,0,75,...,88,0,21000,0,6166905,16445079,752618,NaN,2250,6043.0
137,Zimbabwe,1.7577,90,10,0,14,38,28,6,42,...,196,0,19500,0,5584086,14030368,390757,NaN,0,3229.0

In [5]:
military_power.dtypes

Country                                object
Military Strength Power Index         float64
Aircraft Strength                       int64
Fighter/Interceptor Strength            int64
Attack Aircraft Strength                int64
Transport Aircraft Fleet Strength       int64
Trainer Aircraft Fleet                  int64
Helicopter Fleet Strength               int64
Attack Helicopter Fleet Strength        int64
Tank Strength                           int64
AFV/APC Strength                        int64
Self-Propelled Artillery Strength       int64
Towed Artillery Strength                int64
Rocket Projector Strength               int64
Navy Fleet Strengths                  float64
Aircraft Carrier Fleet Strength       float64
Submarine Fleet Strength              float64
Destroyer Fleet Strength              float64
Frigate Fleet Strength                float64
defense spending budget                 int64
External Debt                           int64
Airport Totals                          int64
Oil Production                          int64
Oil Consumption                         int64
Proven Oil Reserves                     int64
Available Manpower                      int64
Total Population                        int64
Total Square Land Area                  int64
Total Coastline Coverage              float64
Total Waterway Coverage                 int64
Total Border Coverage                 float64
dtype: object